export const menuTokati = {
  menu: [
    {
      langKey: "en",
      items: [
        {
          menuNumber: 1,
          category: "Spreads",
          image: "/menu/foto.jpg",
          title: "Tzatziki",
          ingredients: " ",
          price: "3,5",
        },
        {
          menuNumber: 2,
          category: "Spreads",
          image: "/menu/foto.jpg",
          title: "Tamaras Fish Roe (white)",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 3,
          category: "Spreads",
          image: "/menu/foto.jpg",
          title: "Eggplant spread",
          ingredients: " ",
          price: "3,5",
        },
        {
          menuNumber: 4,
          category: "Spreads",
          image: "/menu/foto.jpg",
          title: "Tirokafteri cheese spread",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 5,
          category: "Spreads",
          image: "/menu/foto.jpg",
          title: "Garlic spread",
          ingredients: " ",
          price: "3",
        },
        {
          menuNumber: 6,
          category: "OusoMezze",
          image: "/menu/foto.jpg",
          title: "Ouzo +Mezze for 1",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 7,
          category: "OusoMezze",
          image: "/menu/foto.jpg",
          title: "Mezze for 2",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 8,
          category: "OusoMezze",
          image: "/menu/foto.jpg",
          title: "Medium Mezze Dish",
          ingredients: " ",
          price: "8",
        },
        {
          menuNumber: 9,
          category: "OusoMezze",
          image: "/menu/foto.jpg",
          title: "Large Mezze Dish",
          ingredients: " ",
          price: "15",
        },
        {
          menuNumber: 10,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Rise",
          ingredients: " ",
          price: "2,5",
        },
        {
          menuNumber: 11,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Yellow hard cheese deepfried balls",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 12,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Fried Eggplants",
          ingredients: " ",
          price: "3,5",
        },

        {
          menuNumber: 13,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Roasted eggplants",
          ingredients: "+ feta, garlic, vinegar, olive oil, tomato",
          price: "5",
        },
        {
          menuNumber: 14,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Fried zuccini",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 15,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Fried Kefalotyri cheese",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 16,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Grilled Kefalotyri cheese",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 17,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Feta",
          ingredients: "served with oil & oregano",
          price: "3",
        },
        {
          menuNumber: 18,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Roasted halloumi cheese",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 19,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Fried peppers",
          ingredients: " ",
          price: "3",
        },
        {
          menuNumber: 20,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Handmade vine leaves with rice",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 21,
          category: "Appetizers",
          imag4e: "/menu/foto.jpg",
          title: "French Fries",
          ingredients: " ",
          price: "0",
        },
        {
          menuNumber: 22,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Mastello cheese from Chios",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 23,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Grilled vegetables",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 24,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Grilled mushrooms",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 25,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Bouyurdi",
          ingredients:
            "baked/tomato, feta, cheese, chili pepper, oregano, olive oil",
          price: "5",
        },
        {
          menuNumber: 26,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Bread",
          ingredients: " ",
          price: "1",
        },
        {
          menuNumber: 27,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Dough Pies",
          ingredients: " ",
          price: "0,5",
        },
        {
          menuNumber: 28,
          category: "Appetizers",
          image: "/menu/foto.jpg",
          title: "Fried feta cheese",
          ingredients: " ",
          price: "5",
        },
        {
          menuNumber: 29,
          category: "Soups",
          image: "/menu/foto.jpg",
          title: "Fish soup",
          ingredients: " ",
          price: "7",
        },
        {
          menuNumber: 30,
          category: "Soups",
          image: "/menu/foto.jpg",
          title: "Chicken soup",
          ingredients: " ",
          price: "6",
        },
        {
          menuNumber: 31,
          category: "Soups",
          image: "/menu/foto.jpg",
          title: "Vegetable soup",
          ingredients: " ",
          price: "6",
        },
        {
          menuNumber: 32,
          category: "Stews & Baked Dish of the day",
          image: "/menu/foto.jpg",
          title: "Moussaka",
          ingredients: "baked in the oven, ground beef",
          price: "7",
        },
        {
          menuNumber: 33,
          category: "Stews & Baked Dish of the day",
          image: "/menu/foto.jpg",
          title: "Gemista stuffed peppers",
          ingredients: "ground beef",
          price: "7",
        },
        {
          menuNumber: 34,
          category: "Stews & Baked Dish of the day",
          image: "/menu/foto.jpg",
          title: "Stews & Baked Dish of the day",
          ingredients:
            "Seasonal fresh stews, green beans, okra, spinach & rice stew",
          price: "6",
        },
        {
          menuNumber: 35,
          category: "Stews & Baked Dish of the day",
          image: "/menu/foto.jpg",
          title: "Braised veal stew",
          ingredients: " ",
          price: "9",
        },
        {
          menuNumber: 36,
          category: "Stews & Baked Dish of the day",
          image: "/menu/foto.jpg",
          title: "Pork knuckle",
          ingredients: "baked in the oven with potatoes",
          price: "8",
        },
        {
          menuNumber: 37,
          category: "Savory smenuNumberers",
          image: "/menu/foto.jpg",
          title: "Smoked mackerel",
          ingredients: "",
          price: "6",
        },
        {
          menuNumber: 38,
          category: "Savory smenuNumberers",
          image: "/menu/foto.jpg",
          title: "Anchovies",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 39,
          category: "Savory smenuNumberers",
          image: "/menu/foto.jpg",
          title: "Marinated anchovies",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 40,
          category: "Savory smenuNumberers",
          image: "/menu/foto.jpg",
          title: "Lakerda",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 41,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Tomato salad",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 42,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Greek salad",
          ingredients: " ",
          price: "6",
        },
        {
          menuNumber: 43,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Lettuce",
          ingredients: "Fresh letucce, chives, dill, lemon, olive oil",
          price: "5",
        },
        {
          menuNumber: 44,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Beetroot",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 45,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Broiled Greens",
          ingredients: " ",
          price: "4",
        },
        {
          menuNumber: 46,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "To Kati Allo",
          ingredients:
            "Baby Rocket, beetroot, spinach, cherry tomatoes, fresh peanuts, manouri cheese, mango dressing",
          price: "8",
        },
        {
          menuNumber: 47,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Parmesan",
          ingredients:
            "Salad Mix: fresh peanuts, walnuts, parmesan, dressing, olives from HalkmenuNumberiki",
          price: "7,5",
        },
        {
          menuNumber: 48,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Pikantiki",
          ingredients:
            "Cabbage, carrot, celery, green and red peppers, vinegar, olive oil",
          price: "4",
        },
        {
          menuNumber: 49,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Chili green pepper",
          ingredients: " ",
          price: "2",
        },
        {
          menuNumber: 50,
          category: "Salads",
          image: "/menu/foto.jpg",
          title: "Sweet Red Pepper",
          ingredients: "Oil and Vinegar",
          price: "3,5",
        },
        {
          menuNumber: 51,
          category: "Lamb",
          image: "/menu/foto.jpg",
          title: "Lamb chops (300gr)",
          ingredients: "served with mashed or baked potatoes",
          price: "11,5",
        },
        {
          menuNumber: 5100,
          category: "Lamb",
          image: "/menu/foto.jpg",
          title: "Lamb chops Price/kg",
          ingredients: "served with mashed or baked potatoes ",
          price: "30",
        },
        {
          menuNumber: 52,
          category: "Skewers",
          image: "/menu/foto.jpg",
          title: "Spit Pancetta 300gr",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 53,
          category: "Skewers",
          image: "/menu/foto.jpg",
          title: "Kokoretsi 250gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 54,
          category: "Skewers",
          image: "/menu/foto.jpg",
          title: "Kontosouvli Pork 300gr",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 55,
          category: "Skewers",
          image: "/menu/foto.jpg",
          title: "Spit lamb 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 56,
          category: "Skewers",
          image: "/menu/foto.jpg",
          title: "Spit Goat 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 57,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Chicken fillet",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 58,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Chicken fillet with mushroom cream",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 59,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Chicken skewer",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 60,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Pork tenderioin with Mushroom cream",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 61,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Pancetta",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 62,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Burger stuffed with cheese",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 63,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Chicken wings",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 64,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Pork with mushroom cream",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 65,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Burger 300gr To Kati Allo",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 66,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Burger stuffed with cheese",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 67,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Pork steak 500gr",
          ingredients: "",
          price: "11",
        },
        {
          menuNumber: 68,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Pork steak 350gr",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 69,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Chicken schnitzel",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 70,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Sutzukaki To Kati Allo",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 71,
          category: "Meat Dishes",
          image: "/menu/foto.jpg",
          title: "Tigania pork pan",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 72,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Rib Steak with baked potatoes 500gr",
          ingredients: "",
          price: "13",
        },
        {
          menuNumber: 73,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Beef fillet with mashed sweet potatoes 300gr",
          ingredients: "",
          price: "18",
        },
        {
          menuNumber: 74,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Young bull steak 400gr",
          ingredients: "",
          price: "13",
        },
        {
          menuNumber: 75,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Beef Burger 300gr",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 76,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Dishes for 1 persons (1-pax platter)",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 77,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Dishes for 2 persons (2-pax platter)",
          ingredients: "",
          price: "14",
        },
        {
          menuNumber: 78,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Dishes for 4 persons (4-pax platter)",
          ingredients: "",
          price: "28",
        },
        {
          menuNumber: 79,
          category: "Beef",
          image: "/menu/foto.jpg",
          title: "Dishes for 8 persons (8-pax platter)",
          ingredients: "",
          price: "60",
        },
        {
          menuNumber: 80,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Shrimp Spaghetti",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 81,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Roasted squmenuNumber 400gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 82,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Stuffed squmenuNumber 400gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 83,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Roasted sardine 250gr",
          ingredients: "",
          price: "6",
        },
        {
          menuNumber: 84,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Grilled octopus",
          ingredients: "",
          price: "12",
        },
        {
          menuNumber: 85,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Sea bream (kg )",
          ingredients: "",
          price: "30",
        },
        {
          menuNumber: 86,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Sea bass (kg)",
          ingredients: "",
          price: "35",
        },
        {
          menuNumber: 87,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Stripped seabream (kg)",
          ingredients: "",
          price: "40",
        },
        {
          menuNumber: 88,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Fresh grilled shrimp 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 880,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Fresh grilled shrimp Price/kg",
          ingredients: "",
          price: "40",
        },
        {
          menuNumber: 89,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Fresh shrimp from Kallikratia (kg)",
          ingredients: "",
          price: "65",
        },
        {
          menuNumber: 90,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Grilled cod (kg)",
          ingredients: "",
          price: "35",
        },
        {
          menuNumber: 91,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Red snapper",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 92,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Sole fish",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 93,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Salmon",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 94,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Swordfish fillet",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 95,
          category: "Grilled Seafood Dishes",
          image: "/menu/foto.jpg",
          title: "Lobster",
          ingredients: "",
          price: "0",
        },
        {
          menuNumber: 96,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried squmenuNumber (frozen) 300gr",
          ingredients: "",
          price: "12",
        },
        {
          menuNumber: 97,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fresh squmenuNumber (fried) 300gr",
          ingredients: "",
          price: "12",
        },
        {
          menuNumber: 98,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Red mullet 300gr",
          ingredients: "",
          price: "12,5",
        },
        {
          menuNumber: 980,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Red mullet Price/kg",
          ingredients: "",
          price: "50",
        },

        {
          menuNumber: 99,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried anchovy 250gr",
          ingredients: "",
          price: "6",
        },
        {
          menuNumber: 100,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried fish tails 300gr",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 101,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Saganaki fish tails",
          ingredients: "",
          price: "9",
        },
        {
          menuNumber: 102,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried shrimp 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 103,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Saganaki shrimp 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 104,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Saganaki shrimp with white sauce and garlic 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 105,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried cod 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 106,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried cod with garlic spread (frozen) 300gr",
          ingredients: "",
          price: "10",
        },
        {
          menuNumber: 107,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Fried mussels 250gr",
          ingredients: "",
          price: "7,5",
        },
        {
          menuNumber: 108,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Steamed mussels 500gr",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 109,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Saganaki mussels ",
          ingredients: "white sauce and spicy feta",
          price: "8",
        },
        {
          menuNumber: 110,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Cuttlefish stew 300gr",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 111,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Mussel Pilaf",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 112,
          category: "Seafood",
          image: "/menu/foto.jpg",
          title: "Seafood risotto",
          ingredients: "octopus, mussels, shrimp, fresh squmenuNumber, saffron",
          price: "10",
        },
        {
          menuNumber: 113,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Mamos beer",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 114,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Kaiser beer",
          ingredients: "",
          price: "4,5",
        },
        {
          menuNumber: 115,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Amstel beer",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 116,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Heineken beer",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 117,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Fix beer",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 118,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Drinks",
          ingredients: "Mythos beer",
          price: "4",
        },
        {
          menuNumber: 119,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Alfa beer",
          ingredients: "",
          price: "4",
        },
        {
          menuNumber: 120,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Large draight beer",
          ingredients: "",
          price: "4,5",
        },
        {
          menuNumber: 121,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Small draight beer",
          ingredients: "",
          price: "3,5",
        },
        {
          menuNumber: 122,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Malamatina retsina",
          ingredients: "",
          price: "3,5",
        },
        {
          menuNumber: 123,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Georgiadis retsina",
          ingredients: "",
          price: "3,5",
        },
        {
          menuNumber: 124,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Kechribari retsina",
          ingredients: "",
          price: "3,5",
        },
        {
          menuNumber: 125,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Vasiliki retsina",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 126,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Unbotled white wine 500ml",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 127,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Unbotled red wine 500ml",
          ingredients: "",
          price: "2,5",
        },
        {
          menuNumber: 128,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "White Wine/Glass",
          ingredients: "",
          price: "5",
        },
        {
          menuNumber: 129,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Red Wine/Glass",
          ingredients: "",
          price: "2,5",
        },
        {
          menuNumber: 130,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Tsipouro/Glass",
          ingredients: "",
          price: "2,5",
        },
        {
          menuNumber: 131,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Unbotled Tsipouro 250ml",
          ingredients: "",
          price: "6",
        },
        {
          menuNumber: 132,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Ouzo Tsantali 200ml",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 133,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Ouzo Plomari 200ml",
          ingredients: "",
          price: "8",
        },
        {
          menuNumber: 134,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Cognac",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 135,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Whiskey",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 136,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Vodka",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 137,
          category: "Drinks",
          image: "/menu/foto.jpg",
          title: "Gin",
          ingredients: "",
          price: "7",
        },
        {
          menuNumber: 138,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Sour Cherry",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 139,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Orange",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 140,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Peach",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 141,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Fruit Juices",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 142,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Coca-Cola",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 143,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Coca-Cola Zero",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 144,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Lemonade",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 145,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Orangeade",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 146,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Sprite",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 147,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Soda",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 148,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Ice-teaWater 1L",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 149,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Water 1L",
          ingredients: "",
          price: "1",
        },
        {
          menuNumber: 150,
          category: "Fruit Juices",
          image: "/menu/foto.jpg",
          title: "Water 500ml",
          ingredients: "",
          price: "0,5",
        },
        {
          menuNumber: 151,
          category: "Coffee-tea",
          image: "/menu/foto.jpg",
          title: "Greek coffee",
          ingredients: "",
          price: "2",
        },
        {
          menuNumber: 152,
          category: "Coffee-tea",
          image: "/menu/foto.jpg",
          title: "Nescafe (notcoffee)",
          ingredients: "",
          price: "2,5",
        },
        {
          menuNumber: 153,
          category: "Coffee-tea",
          image: "/menu/foto.jpg",
          title: "Frape (iced coffee)",
          ingredients: "",
          price: "2,5",
        },
        {
          menuNumber: 154,
          category: "Coffee-tea",
          image: "/menu/foto.jpg",
          title: "Tea",
          ingredients: "",
          price: "1,5",
        },
      ],
    }
  ],
  restId: "65df2ccff5b226c499cdd04a",
};